name: CI

on: [push, pull_request, workflow_dispatch, repository_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1
    - uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    # - uses: krdlab/setup-haxe@v1
    - name: Build Site
      run: |
        npm install
        npm run build:css
        npx @11ty/eleventy --pathprefix=haxeflixel.com
    - name: Deploy Master
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        publish_dir: ./out
        force_orphan: true
